title: Canada Modafinil
description: Information About Modafinil

url: http://www.canadamodafinil.com
baseurl: "http://www.canadamodafinil.com"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 #- title: About
 #  url: /about

social:
   github: 
   twitter: 
   facebook: 
   email: canmodaf@gmail.com

google_analytics: #"UA-42859700-3"
